apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-deployment
  labels:
    app: default
spec:
  selector:
    matchLabels:
      app: default
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: default
          image: jashwa/capdefault
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: default-service
spec:
  selector:
   app: default
  ports:
   - port: 85
     protocol: TCP
     targetPort: 80
  type: LoadBalancer
